### ISSUE TITLE
A question about the region of this sample

### ISSUE THREAD

**Issue by Kinglon1317** [aws-samples/amazon-eks-cdk-blue-green-cicd#10]
Hi,thanks for sharing this sample to everyone, it is very nice and very useful to have a test to using cdk to deploy B/G on AWS EKS.
May i ask you a question about the using region?
Is this sample just recommend using in us-east-2(Ohio) or us-west-2(Oregon) currently, right?
As it will occur an error when i using in ap-east-1, like below:
**Remote function error: UnrecognizedClientException: The security token included in the request is invalid.**
It caused CdkStackALBEksBg create failed.
Could you give me some addvice for this error?Many thanks.

**Comment by nvaidya1** [comment]
Hi @Kinglon1317, apologize for my late response and thanks for reaching out. I haven't encountered issues with other regions, as long as all services used are supported in that region. On which terminal were you running cdk commands? You may need to make sure that temporary credentials are disabled and provide that instance with an IAM role with sufficient access to operate on EKS. In GitHub I have provided a very short description, but may want to check this link for a more elaborate self-guided workshop of these steps: http://cicd-pipeline-cdk-eks-bluegreen.workshop.aws
Please try those steps and let me know if you still see the issue. I will close this "issue" for now, but please feel free to re-open if you see the issue. Please also provide more details around which specific steps are you seeing the issue, etc..

Always, appreciate your feedback.
