### ISSUE TITLE
CDK Deployment Failing at "CdkStackALBEksBg-awscdkawseksClusterResourceProviderNestedStack"

### ISSUE THREAD

**Issue by gmedard** [aws-samples/amazon-eks-cdk-blue-green-cicd#16]
Receiving the following error at the nested stack "CdkStackALBEksBg-awscdkawseksClusterResourceProviderNestedStack"

ProviderframeworkonTimeout0B47CA38 --> Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 9e50dd6e-ca8c-4138-8507-e984cf46cc33, Extended Request ID: null)" (RequestToken: 526f9b43-d827-cd1f-8941-5f1aacacb555, HandlerErrorCode: InvalidRequest)

I'm not sure where the nested stack code is. Please advise where I can update this Lambda runtime?

Thank You!

**Comment by matlaver** [comment]
I have submitted a PR to address this issue: https://github.com/aws-samples/amazon-eks-cdk-blue-green-cicd/pull/17
