### ISSUE TITLE
Missing Kubernetes version

### ISSUE THREAD

**Issue by spachava753** [aws-samples/amazon-eks-cdk-blue-green-cicd#2]
It seems like eks.Cluster module requires a KubernetesVersion. Adding the KubernetesVersion fixed it for me.
**Previous:**
```
 const cluster = new eks.Cluster(this, 'Cluster', {
      vpc,
      defaultCapacity: 2,
      mastersRole: clusterAdmin,
      outputClusterName: true,
    });
```
**Suggested:**
```
 const cluster = new eks.Cluster(this, 'Cluster', {
      vpc,
      version: eks.KubernetesVersion.V1_16,
      defaultCapacity: 2,
      mastersRole: clusterAdmin,
      outputClusterName: true,
    });
```

**Comment by nvaidya1** [comment]
Hi @spachava753, thanks for bringing this to my attn. The latest CDK construct is making it mandatory to select the EKS version. I have updated README instructions along with package.json file to freeze the CDK version on which the workshop was tested. I have added a note here in the README.
Appreciate your feedback & thanks for your time.

I am closing this case for now, however, if you see any discrepancies, please feel free to re-open or file a new issue.
