### ISSUE TITLE
Deployment Fails | no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by SystemicEmotions** [aws-samples/amazon-eks-cdk-blue-green-cicd#4]
App deployment fails, you might need to edit the below yaml files with correct apiVersion . 
flaskALBGreen.yaml
flaskALBBlue.yaml

Correct apiVersion
apiVersion: apps/v1

**Comment by nvaidya1** [comment]
@SystemicEmotions, thank you for bringing it to attn, looks like the behavior changed after EKS1.16. I have updated the instructions and the yaml files and tested it, please let me know if you see any further discrepancies.
I am closing this case, however, if you see an issue, please feel free to re-open. Thanks for your time and contribution.
