### ISSUE TITLE
Load balancer failed to register healthy targets. 

### ISSUE THREAD

**Issue by SystemicEmotions** [aws-samples/amazon-eks-cdk-blue-green-cicd#5]
Registered targets under both the target groups were showing unhealthy as request was getting timeout. 
As a resolution, allow required ports  in EC2 instance security group from load balancer SG to register the targets successfully and you will be able to see the website !!

**Comment by nvaidya1** [comment]
@SystemicEmotions, thank you for bringing it to attn, looks like the behavior changed after EKS1.16. I have updated the instructions and tested it, please let me know if you see any further discrepancies.
I am closing this case, however, if you see an issue, please feel free to re-open. Thanks for your time.
