### ISSUE TITLE
Could not access Jenkins web interface with error "jenkins.model.InvalidBuildsDir"

### ISSUE THREAD

**Issue by Nutchanon-L** [aws-samples/amazon-eks-cdk-blue-green-cicd#6]
Hi,

As I follow the workshop "**Building CICD pipeline with Jenkins on Amazon ECS**" (https://third-party-integration-codepipeline-eks-bluegreen.workshop.aws/en/). 

During the "2. IaC Launch" step, I found error when I tried to access URL of Jenkins Web-Interface from CloudFormation Output after CloudFormation was deployed. The ELB shown "OutOfService" status. So, I changed security group of EC2 to allow to access port 8080 directly. The error message shown as below.

**Error:**
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not exist and 
probably cannot be created
at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3085)
at jenkins.model.Jenkins.loadConfig(Jenkins.java:3009)
Caused: java.io.IOException
...

I did research and found that the error came from Jenkins directory permission/owner on "/data/jobs" path which is created by extract from another github package (https://github.com/aws-samples/amazon-eks-cdk-blue-green-cicd/blob/dde7fb74666328ac338c87b6aae2fae4a72c7053/cicd/jenkins-ecs-workshop.json#L553). Btw, you have changed the permission at line 551 which is before the package is extracted (https://github.com/aws-samples/amazon-eks-cdk-blue-green-cicd/blob/dde7fb74666328ac338c87b6aae2fae4a72c7053/cicd/jenkins-ecs-workshop.json#L551). Should you change the permission after line 553 to fix this?

I have manually changed the owner to "1000:1000" on my workshop and it works properly.

**Comment by nvaidya1** [comment]
Hi @Nutchanon-L, thank you for your feedback. I have an updated json file (jenkins-ecs-workshop3.json) with a few modifications & have updated the workshop too. This should resolve the issue as well as also configure Jenkins for its worker nodes.
I will close this issue for now, but please feel free to let me know if you encounter any further issues OR questions.
Thanking you for your time and efforts to provide valuable feedback.
