### ISSUE TITLE
Documentation updates needed

### ISSUE THREAD

**Issue by paulramsey** [aws-samples/amazon-eks-cdk-blue-green-cicd#7]
While working through the [workshop](https://cicd-pipeline-cdk-eks-bluegreen.workshop.aws/en/), I identified the following issues that need to be updated in the documentation:

- Step 2(b) in "Setting up Cloud9 IDE": New EC2 console introduced a necessary change. Attaching an IAM role moved to Actions > Security > Modify IAM role in the new EC2 console. Needs updated instructions and a new screenshot.
- Step 1(c) in "Prepare and Download packages": Formatting error in cdk command. Use "cdk --version", not "cdk -version".
- Step 1(d) in "Prepare and Download packages": There is no untar operation, but the documentation says to ignore errors in the untar command. 
- Step 1(e) in "Prepare and Download packages": There is no CodeCommit operation, so the CodeCommit access via http link is either not need or is premature.
- Step 6 in "CDK Launch": The step says that you deploy the CDKToolkit to trigger the CloudFormation stack to execute. This isn't strictly true. The CDKToolskit stack is deployed when you run "cdk bootstrap", and it simply deploys an S3 bucket to hold assets related to cdk execution. The "cdk deploy" command actually launches 4 new CloudFormation stacks (starting with "CdkStackALBEksBg"), and it doesn't touch the CDKToolkit stack at all.
- Step 1(a) in "Access EKS": The line that reads "Now under Load Balance -> Select Instances Tab" should be changed to "Now under Load Balancing -> Target groups, Select the Monitoring Tab".

**Comment by nvaidya1** [comment]
Hi @paulramsey, apologize for the late response. I have addressed all your documentation points. Thank you for providing the detail & helping us improve our documentation. I will close this Issue now, however, please feel free to re-open / open a new one if you have any feedback to improve the documentation further. 
Appreciate your time and efforts.
