### ISSUE TITLE
Load Balancers are not coming up 

### ISSUE THREAD

**Issue by subrat82** [aws-samples/amazon-eks-cdk-blue-green-cicd#8]
I followed this website and worked on it , how ever, where it says that errors like:

and when i see the config file value: 
the server url is something like this : https://B178A9BE7A266F1715BE1B6506E72C5A.gr7.us-west-2.eks.amazonaws.com
i dont know whagt is this gr7 

getting credentials: exec: exit status 255
I0122 22:06:07.360209 7877 helpers.go:221] Connection error: Get https://B178A9BE7A266F1715BE1B6506E72C5A.gr7.us-west-2.eks.amazonaws.com/api?timeout=32s: getting credentials: exec: exit status 255

Getting this error on kubectl get nodes and also there are no LB spun up on AWS.

**Comment by nvaidya1** [comment]
Hi @subrat82, the application is accessed via ELB and the above link looks incorrect. You would need to bind the EKS context as explained in the workshop (from CloudFormation template) before trying to access EKS nodes. Please run through all steps explained in "Step2: Configure EKS environment:" section.
I will close this issue for now.
